### ISSUE TITLE
2. Tag - Kochel am See nach Ehrwald

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#2]
t 03:11
s 61,3 km
hm up 970 m
hm down 600 m

 https://www.komoot.de/tour/465757894?share_token=a52dnrtKeCs5ngypDALgfsxClIUzsiLkPVPIfXevyDhP5zkAEq&ref=wtd

**Comment by BeWi60** [comment]
Guten Morgen und ein Glückauf an den Kochelsee.Ich hoffe das du dich etwas regenerieren konntest.
Heute steht ja ein anspruchsvoller Trail vor dir!
Mal schauen wie du fährst? Schade dass das Wetter noch nicht so richtig mitspielt. 
Aber spätestens in Italien scheint die Sonne.
Poste doch auch mal ein Foto mit deinem Zelt, muss ja auch eine Light-Version sein.

**Comment by splosch** [comment]
Also die Nacht war mäßig und bin ständig wegen der Kälte aufgewacht, hab ja nur nen Dünnen Hüttenschlafsack, wenn es noch kälter wird kann ich das so nicht machen. hatte dann gegen 3 die tolle Idee Fußwärmer aufzukleben das gab nochmal ein paar Stunden Schlaf, ab 4 hat's dann durchgeregnet bis eben

**Comment by splosch** [comment]
Mußte die Tour im Süden um den Kochelsee abbrechen und bin dann im Norden rum, Strasse, Meter machen.
Die Südseiten-Höhenmeter hätten mich gekillt. War "gerade so noch fahrbar steil"...

![IMG_20210828_102411.jpg](https://user-images.githubusercontent.com/666934/131215493-589c26b4-ec82-42ee-acc2-0e37bb904b91.jpg)

**Comment by Nifflerin** [comment]
Oh jeh hört sich an als nimmst du gerade alles mit was sich dem Unterfangen in den Weg stellen will… Durchhalten, Wetter wird nach dem Wochenende definitiv besser. Ich drücke die Daumen für ordentliche Straßen und ein warmes, trockenes Nachtquartier!

**Comment by splosch** [comment]
Kurz vor Garmisch, ich bin jetzt in Voller Schutzausrüstung, und mein Wärmehaushalt stabilisiert sich. Nasse Schuhe sind eben Mist. 
Die Entscheidung die Höhenmeter heute früh gegen Strecke zu tauschen find ich mittlerweile immer besser :) 
![IMG_20210828_141618.jpg](https://user-images.githubusercontent.com/666934/131217646-df3fccf0-aaaf-4f2d-8bc2-8312748085b9.jpg)

Die Berge in Wolken, aber bisher seid ca 11Uhr regenfrei.

**Comment by BeWi60** [comment]
Finde Deine Entscheidung mit der Straße auch sehr gut.  Kannst im sonnigen Süden sicher noch coole Trails fahren....
Nasse und kalte Füße haben mir `auch` schon mal massive Probleme bereitet.  Füße trocknen und Folietüte drüber dann nasse Socken und nasse Schuhe obendrauf. Ist im ersten Moment unangenehm aber hält Füße trocken und etwas wärmer.

**Comment by splosch** [comment]
Zeit endlich Mal ne Unterkunft klarzumachen... Sehnsucht nach Sauna, Badewanne oder zumindest den Föhn damit ich die Sachen trocknen kann 👣

**Comment by Brasina** [comment]
Jeden Kilometer wird es 0,1 Grad wärmer. Durchhalten es lohnt sich🙂.

**Comment by Lassknacken** [comment]
Hallo, Zimmerservice?
Können Sie bitte mal schauen? In dem Zimmer nebenan läuft seid 3 Stunden der Föhn. Hoffentlich ist da nichts passiert.
😂😂😂

Ride on, wir kommen nach!

**Comment by splosch** [comment]
> Jeden Kilometer wird es 0,1 Grad wärmer. Durchhalten es lohnt sich🙂.

Oh darauf baue ich - leider Hält der Wetterfrosch dagegen heute 11 morgen 8 und oben schneits...

Aber das sind die Sorgen von Zukunftsmario

![IMG_20210828_163404.jpg](https://user-images.githubusercontent.com/666934/131227231-71cc1ef6-5df0-4d63-a040-b1b75fd83f4e.jpg)

**Comment by splosch** [comment]
> Zeit endlich Mal ne Unterkunft klarzumachen... Sehnsucht nach Sauna, Badewanne oder zumindest den Föhn damit ich die Sachen trocknen kann 👣

Hatte im Wald kurz vor der AT-Roaming Grenze ordentlich 4g ... Von 3G halten die hier augenscheinlich eh nicht so viel.

Jedenfalls per Booking noch flott für den Abend ne Pension+Frühstück klargemacht. Juhu.

Nach Ankunft sofort in den Wasch und Trockenmodus gewechselt:

![IMG_20210828_182703.jpg](https://user-images.githubusercontent.com/666934/131227409-c41b5ca0-14c2-4559-a554-ca688f3e77ce.jpg)

**Comment by BeWi60** [comment]
Wo hast du denn dein Nachtlager aufgeschlagen. Hast du Ehrwald erreicht?

**Comment by splosch** [comment]
> Wo hast du denn dein Nachtlager aufgeschlagen. Hast du Ehrwald erreicht?

Ich bin in Biberwier knapp neben Ehrwald - im Gasthaus Panorama.
... Apropos aufgeschlagen.... Das Zelt stand aufgeschlagen neben meinem Bett  :) 

Habe alles trocken bekommen und die Klamotten gewaschen. Gestern Abend gab es dann noch im Hotel Alpin n Tiroler Gröstel.

Am Tisch neben mir, drei zähledrige Hunde mit Anti-E-Bike Shirts :)

**Comment by BeWi60** [comment]
Gratulation!!! Toll dass du dem Sch.. Wetter trotzt. Hoffe dass du keine gesund bleibst, um die Sonne in Italien zu genießen!!!!!!
