### ISSUE TITLE
3. Tag : Von Ehrwald nach Landeck ... Dann nach Ried im Oberinntal

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#3]
t 04:03 
s 54,1 km + 19km
hm up 610 m + 800 hm
hm down 780 m

https://www.komoot.de/tour/465725601?share_token=a6qSjQdo3jbUOp411NhmFhd4ckSiU3zBl8LDfS1JKqNp8QIR0D&ref=wtd

Wetter ist mies deswegen Versuche ich schneller durchzukommen und peile mal Ried im Oberinntal für heute als Tagesziel an das sind 20km drauf nach Landeck. 

Habe dort auch schon einen [Gasthof](https://www.google.com/travel/hotels/gasthof%20riederstub'n/entity/CgoIgfL705jZlppAEAE?g2lb=2502548%2C2503771%2C2503781%2C4258168%2C4306835%2C4317915%2C4371334%2C4401769%2C4419364%2C4429192%2C4515404%2C4545890%2C4549823%2C4596364%2C4605861%2C4270859%2C4284970&hl=de-AT&gl=at&ssta=1&q=gasthof%20riederstub%27n&rp=EIHy-9OY2ZaaQBCB8vvTmNmWmkA4AkAASAHAAQI&ictx=1&ved=0CAAQ5JsGahcKEwjw6Omh0NXyAhUAAAAAHQAAAAAQAg&utm_campaign=sharing&utm_medium=link&utm_source=htls&ts=CAESABogCgIaABIaEhQKBwjlDxAJGBoSBwjlDxAJGBsYATICEAAqCQoFOgNFVVIaAA) gefunden der günstige Zimmer hat.

067763806762
Ried im Oberinntal 3, 
6531 Ried im Oberinntal

**Comment by BeWi60** [comment]
Den Tag musst du noch durchstehen. Die Regenfront bleibt an den Nordhängen der Alpen hängen und Übermorgen bist du in der Sonne.
Hoffe du schaffst den Gasthof in Ried. Drücke die Daumen.

**Comment by splosch** [comment]
Bin jetzt schon in Zams und ess erstmal Pizza -lief super heute, kein Regentropfen! ![IMG_20210829_105358.jpg](https://user-images.githubusercontent.com/666934/131249600-3fb437f3-683e-48d0-9f6d-3cd7f31df90c.jpg)
![IMG_20210829_132300.jpg](https://user-images.githubusercontent.com/666934/131249611-12c15bd6-05c3-41a2-8ccf-87b388c73c86.jpg)
![IMG_20210829_121110.jpg](https://user-images.githubusercontent.com/666934/131249632-f35a6cc8-6724-462b-8b4c-552f0393ac5f.jpg)

**Comment by Lassknacken** [comment]
Müde und Glücklich siehst du aus 😀
War die Tour so steil, wie im Profil?
Wie gehts den Beinen und den Sitzhöckern?

**Comment by splosch** [comment]
> Müde und Glücklich siehst du aus 😀
> War die Tour so steil, wie im Profil?
> Wie gehts den Beinen und den Sitzhöckern?

Ging richtig gut. Bin 18:00 in Ried im Oberinntal im Gasthaus eingecheckt.

Nach Landeck der Anstieg zur Fliessener Platte war super knackig und eine Passage nur haarscharf auf dem letzten Ritzel machbar, denke das Radler und die Pizza haben auch mit getreten.. 🙃.
Die Plattenpassage hab ich nicht geschafft, musste schieben wie auch schon auf den Hinweisschildern stand 🙄, aber das geht wohl auch nur motorisiert oder mit Godlike-Skills.

Hab nen 78jährigen 
an der Platte getroffen der scheint da regelmäßig spazieren zu gehen.

Po ist ok, Babycreme hilft 😁, Beine merk ich schon gut.

**Comment by splosch** [comment]
Vor der Platte ... keine Ahnung warum das beim Track so besonders angemerkt wurde
![IMG_20210829_153918.jpg](https://user-images.githubusercontent.com/666934/131258147-0bc635be-aced-4546-a031-222daf535cce.jpg)


Ok ... Jetzt weiß ich's, Wurzeln und ein glattes Steinklumpenmassiv, nur sehr bedingt befahrbar


![IMG_20210829_155624.jpg](https://user-images.githubusercontent.com/666934/131258123-203e2f7a-343f-4bbd-b1a9-e6aa466545a0.jpg)
Oben auf der Platte.

**Comment by Lassknacken** [comment]
Na dann ruh dich jetzt mal schön aus. Morgen ist schon Halbzeit 🤭
Grüße aus dem Starkregen 🙋‍♂️
