### ISSUE TITLE
4. Tag: Von Landeck nach Nauders

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#4]
t 04:39
s 54,8 km
hm up 1 220 m
hm down 650 m

https://www.komoot.de/tour/465726464?share_token=a4zxKBFV7VHPCPR0e4kc2vdUJVWHPbK1xVc5GLRYxbUJrtfWkG&ref=wtd

**Comment by BeWi60** [comment]
Buon Giorno Großer, genieße das Frühstück im Gasthof, lass dir richtig Eier mit Speck braten!!!
Heute scheintdie letzte Tour im Regen zu sein.Aber am Vormittag sieht es noch gut aus.Ab jetzt kommen die Tage wo ich dich beneiden werde.

**Comment by splosch** [comment]
Hab auch gerade gesehen das zb bei Nauders der Regen erst ab 19uhr Doll wird und ab 14Uhr spürbar. Ich glaub das passt.
![IMG_20210830_081347.jpg](https://user-images.githubusercontent.com/666934/131293624-5510a6f8-acce-4e14-813e-4577a6ffc0af.jpg)

**Comment by splosch** [comment]
So von den eigtl geplanten hm hab ich ja schon 800weg bleiben sanft verteilte 400 und ne kurze Strecke.
Ich fahr nach dem Frühstück einfach mal mit Ziel Nauders los und da Guck ich mir an ob die nächste Etappe noch geht

**Comment by BeWi60** [comment]
Richtig!! Und denk ab jetzt an den guten italienischen  espresso:  un caffe per favore

**Comment by splosch** [comment]
> Richtig!! Und denk ab jetzt an den guten italienischen  espresso:  un caffe per favore

☕👌

**Comment by BeWi60** [comment]
Da könntest du ja heute schon Italien erreichen! Ich bin gespannt wie du voran kommst.

**Comment by Lassknacken** [comment]
wow, du bist ja schon fast im Meran😄
Der Radweg an der Etsch bis Bozen ist super ausgebaut. Freu dich drauf.

**Comment by BeWi60** [comment]
Nur mal so nebenbei: Der Link zur Komot- Tour ist wahrscheinlich falsch. Ist die Tour von Morgen ab Nauders, wobei du da heute vielleicht wirklich schon was abreisssst.

**Comment by splosch** [comment]
Bin eben vor Nauders die Serpentine rauf und geb mir jetzt erstmal nen 🍔.

Der Anstieg auf den bereits etwas festen Beinen hat schon bissl gekniffen hoffe Radler und Carne bringen noch etwas Power für den 2. Abschnitt heute.

**Comment by splosch** [comment]
> Nur mal so nebenbei: Der Link zur Komot- Tour ist wahrscheinlich falsch. Ist die Tour von Morgen ab Nauders, wobei du da heute vielleicht wirklich schon was abreisssst.

Hast recht, korrigiere ich nochmal - jetzt Grad bin ich doch etwas müde.

Da waren heute 2 mal Trail-Passagen drin die nicht fahrbar waren nix mit S1 ... das war vielleicht bergab ne S3/4 und ich musste da rauf  😥 eng, wurzelig und nass.
![IMG_20210830_103041.jpg](https://user-images.githubusercontent.com/666934/131335316-fbbec929-16c7-473e-9964-5ba3e93f17e3.jpg)
![IMG_20210830_103056.jpg](https://user-images.githubusercontent.com/666934/131335348-753c43b9-9acd-4a88-afad-a065d078c34d.jpg)

Naja, war nicht zu lang und ich durfte der Heiße Draht spielen :)

![IMG_20210830_102438.jpg](https://user-images.githubusercontent.com/666934/131335854-c1969bde-278b-4cc6-a3b7-446809180552.jpg)

**Comment by splosch** [comment]
> wow, du bist ja schon fast im Meran😄
> Der Radweg an der Etsch bis Bozen ist super ausgebaut. Freu dich drauf.

Merano ist ~~geknackt~~ noch 7km entfernt... fast!
Der Radweg ist mega und teilweise mörderisch schnell. 🤪
