### ISSUE TITLE
5. Tag: Von Nauders nach Naturns

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#5]
t 4:01
s 75,5 km
hm up 360 m
hm down 1 190 m

https://www.komoot.de/tour/465726464?share_token=a4zxKBFV7VHPCPR0e4kc2vdUJVWHPbK1xVc5GLRYxbUJrtfWkG&ref=wtd

**Comment by splosch** [comment]
Sonne ☀️ überall Sonne.

Ich hab ne Unterkunft in Naturno organisiert muss aber bis 20 Uhr Dasein :)

**Comment by splosch** [comment]
Läuft super - ich werd's wohl gut schaffen in etwas über nee Stunde dazusein![IMG_20210830_175841.jpg](https://user-images.githubusercontent.com/666934/131368723-e7946536-9a37-41d7-a296-38b19f9a414a.jpg)

**Comment by splosch** [comment]
Bin da ☺️

**Comment by Nifflerin** [comment]
Na endlich ☀️! Ab jetzt hoffentlich nur noch so. Krass wie flott du trotz Wetter und Route unterwegs bist, in dem Tempo wäre glatt noch ein Abstecher ans Meer drin… 😄

**Comment by splosch** [comment]
> Bin da ☺️

Irrglaube :/

Das "bin da" galt bei Naturno - aber die Garni ist 8,5km hinter ~~Merano~~Naturno... Argss zu früh gefreut.
Naja jetzt bin ich aber da und Sitz im Zimmer - s gab nochmal ne kleinen 8min extra Anstieg und Schluss ist für heut.... Ausser ich will Pizza dann muss ich nochmal runter in den Ort 🤔🍕

Pizza kostet hier am Standort ca 200hm ... 😎 ... Aussicht ist eben meist gut von oben.


Garni An der Leit
+39 0473 448588
https://maps.app.goo.gl/SV2YzxTvbXGNfoXw8

![IMG_20210830_194228.jpg](https://user-images.githubusercontent.com/666934/131381722-5ad8d6ba-0e90-42fe-91e3-ffed4519cacf.jpg)

**Comment by BeWi60** [comment]
Ich kann es nicht glauben, du hast es in die Sonne geschafft. Glückwunsch,  da ist der Abstecher zum Meer ja wirklich nicht so abwegig....
Schlaf dich aus und freu dich auf den Sonnenaufgang. Und lass dir jetzt Zeit um deine Tour mehr zu genießen!!!!
