### ISSUE TITLE
5. Tag: Von Naturns nach Bozen

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#6]
t 02:45
s 49,4 km
hm up 260 m
hm down 530 m

https://www.komoot.de/tour/465726797?share_token=aHQMmGoLUoi0Ktko47JNExQiNDUHCiI02l3TDQzbm5t1iLl5rw&ref=wtd

**Comment by BeWi60** [comment]
Na wie fühlt sich die italienische Morgenluft an? Da du so schnell im Meraner Land angekommen bist, solltest du die Gegend dir in Ruhe anschauen. Nach Bozen geht es ja auch nur bergab, da ist selbst ein Abstecher nach Dorf Tirol noch drin oder hoch auf den Meraner Höhenweg.
Aber wahrscheinlich willst du doch so schnell wie möglich ins Kletterparadies nach Arcor .
Ich wünsche dir jedenfalls viel Fun in der südlichen Sonne.......

**Comment by splosch** [comment]
Och Sabrina und Benny kommen ja am 4.9. in Arco an, vorher muss ich da nicht sein. Ich hab jetzt 4 Tage und kann die Zeit geniessen und endlich das Zelt wieder auspacken.

**Comment by Lassknacken** [comment]
Nimm den Lift in Vellau und lauf zur Mutspitze👍 Es Lohnt sich.

**Comment by splosch** [comment]
> Nimm den Lift in Vellau und lauf zur Mutspitze👍 Es Lohnt sich.

Die Tour sieht super aus! Allerdings sehe ich da Gehzeit von ca 4-5h bei über 800hm .... Ich komm kaum mehr die Treppe ins 2. OG😅
Und mein Rad mit Zeugs drauf müsste ich am Lift oder in Velau lassen. Kann's zwar minimal sichern aber mit dem Taschenmesser knackt mans

Der Korblift ist aber Hammer - mhhhh was tut er...

**Comment by Lassknacken** [comment]
😂
Dann geh vielleicht lieber runter an die Etsch und halt heute mal die Füße ins Wasser.
Hast ja noch n Paar KM zu trampeln. Tag 7 115km 🤭

**Comment by splosch** [comment]
Kleine Detour nach Dorf Tirol
Entlang der Hänge
https://www.komoot.de/tour/471984008?ref=aso&share_token=a1ChQImg2CD4kcanizktuv3nVPxaxk4JA9r7RFVB7DoTkBQN3H

**Comment by BeWi60** [comment]
Wirst du nicht bereuen. Ist ein schöner  Weg auch mit Blick auf Meraner Ebene (Mutspitze ist natürlich ne andere Hausnummer,) aber es könnten viele Ältere Touris entgegen kommen. 
Aber der Jüngste biste ja auch nicht mehr..sorry...

**Comment by Lassknacken** [comment]
Na wenn du jetzt in Lana bist, kannste auch nach Bozen runter rollen😬

**Comment by splosch** [comment]
> Na wenn du jetzt in Lana bist, kannste auch nach Bozen runter rollen😬

- [x] Bozen

**Comment by splosch** [comment]
Ich bin jetzt auf dem Campingplatz At. Joseph am Kaltener See.

Ankunft schon gegen 18Uhr, der Platz war belegt aber für Rad + 1er-Zelt ist imma a Platzle.

Hier gibt's den Gin Tonic für 4,50€ 🤪

Bin schon kaputt aber der eher entspannte Tag war auch echt Mal ne Wonne![IMG_20210831_101123.jpg](https://user-images.githubusercontent.com/666934/131545741-5598033a-1ccd-4d6f-91f3-739b16686034.jpg)
![IMG_20210831_103243.jpg](https://user-images.githubusercontent.com/666934/131545792-72d7033c-955e-411b-a128-b0094bb70412.jpg)

**Comment by splosch** [comment]
> Wirst du nicht bereuen. Ist ein schöner  Weg auch mit Blick auf Meraner Ebene (Mutspitze ist natürlich ne andere Hausnummer,) aber es könnten viele Ältere Touris entgegen kommen. 
> Aber der Jüngste biste ja auch nicht mehr..sorry...

Mit den etwas ruhigeren Wandergästen hast du wohl Recht - allerdings sind die nur Lustgewandelt und ich schwitzend den Ochsentod rauf gepresst 💪😳 naja so 60% der Rest hätte nicht nur die Ochsen gemeuchelt.
