### ISSUE TITLE
7. Tag: Von Bozen nach Arco/Gardasee

### ISSUE THREAD

**Issue by splosch** [splosch/transalp_log#7]
... ich hoffe das wird schon am Tag 6 sein :)
t 06:55
s 115 km
hm up 360 m
hm down 560 m

https://www.komoot.de/tour/465727092?share_token=apURtf2ydfTquOFLCU2h93TngT8CBEwzCsN49ij7NzXCBJM4Hk&ref=wtd

**Comment by splosch** [comment]
Da ich ja schon so gut im Zielgebiet bin überlege ich einen Seen-Roundtrip...
Nächste mgl. Station:
Molvenosee
Camping Beach Lake of Molveno
+39 0461 586978
https://maps.app.goo.gl/T8JdArLsyoWe9KpY7

**Comment by akoch-tng** [comment]
Wow, du bist jetzt schon richtig weit, und heute ist erst Mittwoch. Du könntest auf jeden Fall da sein vor Plan. Und dann könntest du dich auch im Pool ausruhen bis der Rest eintrifft ;)

**Comment by BeWi60** [comment]
Na da bin ich mal gespannt auf deine heutige Route, welche Seen du noch so ansteuerst.
Frage: Wie lang war denn deine Route von Ried nach Meran?

**Comment by splosch** [comment]
> Na da bin ich mal gespannt auf deine heutige Route, welche Seen du noch so ansteuerst.
> Frage: Wie lang war denn deine Route von Ried nach Meran?

Der direkte Weg laut Google-Maps sind ca.109km viel mehr isses nicht aber etwas bestimmt.

**Comment by splosch** [comment]
Bin heute früh schon 8Uhr vom Zeltplatz gerollt und habe eben in Tramin lecker gefrühstückt.

Der leichte Anstieg war aber schon noch so nett, mein linkes Knie zeigt an das treten gerade keine tolle Sache ist.

Ich habe auch gewaschene und noch nasse Sachen dabei und werde sicher nochmal irgendwo einen Trocken und Schlummerhalt machen.

Die Nacht war OK, selbst bei 14grad bleiben die Füsse kalt, ich versuchs noch eine Nacht mit Schuhe an,.wenn das nix bringt hol ich mir nen Schlafsack oder Dicke Socken.

![IMG_20210901_082449.jpg](https://user-images.githubusercontent.com/666934/131627854-aaa4f400-2d26-481b-a545-f6dc6e348aa3.jpg)

**Comment by Lassknacken** [comment]
Sag Bescheid, wenn wir für dich noch was mitbringen sollen/können.

**Comment by splosch** [comment]
Mein Knie hat nach dem Croissant mit Pistazienfcremefüllung und etwas Voltaren(direkt, ohne Backwaren) keinerlei Einwände zur Weiterfahrt gehabt. 
Bin jetzt kurz vor Trient und gebe mir gleich Mal ne Pizza oder Carne weiß.noch nicht, an der Abfahrt Molveno bin ich vorbeigedüst hab's nicht gerafft

**Comment by BeWi60** [comment]
Das sind ja mal wieder gute Neuigkeiten. Aber bei dem Tempo kannst Du die Gegend doch gar nicht genießen... Oder doch?
Und wie stehts mit dem Sonnenschutz? Den Regenschutz kannst Du jetzt ja mal entsorgen......
Ich bin jedenfalls auch überrascht über Deine Kilometer die du so jeden Tag machst.
Da kannst Du ja mal von Arcor aus den Lago di Tenno aufsuchen, aber da muss das Knie komplett OK sein, sind so um die 700 HM. LG

**Comment by Nifflerin** [comment]
Auch auch ein Stadtbummel in Trient ist schön. Kannst dich und das Knie auf eine Sonnenterrasse pflanzen und ein bisschen von der guten Küche verwöhnen lassen! Das Knie brauchst du am Fels die nächsten Tage ja auch noch… 😉

**Comment by BeWi60** [comment]
Da muss ich zustimmen!! Also mach mal langsamer und gönn Dir ne Pause!!!!

**Comment by splosch** [comment]
Si claro!
Genuss und LF 50

Meran und Bozen fand ich jetzt nicht so prall, Trento Altstadt sehr schöne Gassen - alles voller Leute, richtig Leben in der Bude.

Es gibt Pizza Proscutto Cotto und eine Cola die so richtig zischt.

**Comment by splosch** [comment]
Trient hab ich gestadtbummelt - langweilig - bin neben Trient den Berg rauf. Das ist super! Da oben ist niemand ausser paar Jungs die mit den Mopeds die Serpentine hoch und runterjagen und sich jede Runde den Materialverschleiß abklatschen.

Hier bin ich jetzt - mir geht's prima, keine Schmerzen hab Bock Berge zu fahrn... Immer nur im Tal tztz!
Deswegen die Route geändert fahre.die Kurze aber knackige... Das.Knackige ist schon weg:
[Screenshot_20210901-155940.png](https://user-images.githubusercontent.com/666934/131685686-89d6007b-da04-433c-a0fc-fd120def1a36.png)

**Comment by Lassknacken** [comment]
Ich glaub ich muss dann Sa. Deinen Lenker abmontieren, sonst fährst du noch durch bis Griechenland😂🤷‍♂️

**Comment by splosch** [comment]
![IMG_20210901_164409.jpg](https://user-images.githubusercontent.com/666934/131692519-117bac05-1277-4ea9-912c-3bad20338d0f.jpg)

**Comment by splosch** [comment]
Habe eben mit Arco Camping telefoniert und darf heute schon drauf, habe den Zugangscode und bin bis morgen auf Stellplatz 6 beheimatet - cool dann kann ich auch vor der Ankunft noch was essen gehen

**Comment by splosch** [comment]
> Da muss ich zustimmen!! Also mach mal langsamer und gönn Dir ne Pause!!!!

Nich alle ❗ allemachen :)

Ich hab mir das dreimal überlegt und weil's.so gut geht heute rolle ich durch und morgen ist Tutto kometto Pause - kein Rad - danach geht ich mal nen Tag Wandern oder schwimmen, bevor Benny mich wieder Nassmacht 😅

**Comment by splosch** [comment]
Bin da 🙂

**Comment by BeWi60** [comment]
Gratulation , verrückter Kerl, kannst fast nicht von mir haben????? Freue mich für Dich.
